# Generated by Django 4.2 on 2023-05-06 23:04

from django.db import migrations, models
import django.db.models.deletion
import profile_picture.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('main', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to=profile_picture.models.get_profile_picture_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_profile.profile')),
            ],
        ),
    ]
